name: tf-sparse
channels:
  - nvidia
  - conda-forge
dependencies:
  - cmake
  - gxx=10.3.0
  - python=3.9
#  - cudatoolkit=11.2.2
  - cuda-toolkit=12.0
  - cuda-nvcc=12.0
  - cudnn=8.1.0
  - doxygen
  - pip
  - pip:
      - tensorflow
# conda variables:
# BROKEN!
#  LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$CONDA_PREFIX/lib/
